<?xml version="1.0" ?>
<robot name="rob1" xmlns:xacro="http://ros.org/wiki/xacro">
    
    <!-- ****************** INCLUDES *******************************  -->
 
    <xacro:include filename="material.xacro"/>
    <xacro:include filename="inertial.xacro"/>


    <!-- ****************** ROBOT CONSTANTS *******************************  -->
    <!-- Define the size of the robot's main chassis in meters x y z-->
    <xacro:property name="base_width" value="0.7"/>
    <xacro:property name="base_length" value="0.39"/>
    <xacro:property name="base_height" value="0.20"/>
        
    <!-- Define the shape of the robot's two back wheels in meters -->
    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_width" value="0.02"/>

    <!-- x-axis points forward, y-axis points to left, z-axis points upwards -->
    <!-- Define the gap between the wheel and chassis along y-axis in meters -->
    <xacro:property name="wheel_ygap" value="0.25"/>

    <!-- Position the wheels along the z-axis -->
    <xacro:property name="wheel_zoff" value="0.05"/>

    <!-- Position the wheels along the x-axis -->
    <xacro:property name="wheel_xoff" value="0.221"/>

    <!-- Position the caster wheel along the x-axis -->
    <xacro:property name="caster_xoff" value="0.217"/>


    <!-- ****************** ROBOT BASE FOOTPRINT ***************************  -->
    <!-- Define the center of the main robot chassis projected on the ground -->	
    <link name="base_link"/>
    
    <joint name="corps_joint" type="fixed">
        <parent link="base_link"/>
        <child link="corps_link" />
        <origin xyz="${-base_width/2.0} 0 ${base_height/2+wheel_radius}" rpy="0 0 0"/>
    </joint>
    <!-- ********************** ROBOT BASE *********************************  -->
    <link name="corps_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>            
            </geometry>
            <material name="red"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_width}  ${base_length} ${base_height}"/>  
            </geometry>
        </collision>

        <xacro:box_inertia m="1.0" w="${base_width}" d="${base_length}" h="${base_height}"/> 
    </link>
  <!-- *********************** DRIVE WHEELS LINKS ******************************  -->
   <link name="left_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="white"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
           <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <xacro:cylinder_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}"/> 
    </link>

   <link name="right_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>

        </geometry>
        <material name="white"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
           <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <xacro:cylinder_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}"/> 
    </link>

  <!-- *********************** DRIVE WHEELS JOINTS ******************************  -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${wheel_ygap} ${wheel_radius}" rpy="0 0 0"/>
        <limit effort="30" velocity="1.0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 -${wheel_ygap} ${wheel_radius}" rpy="0 0 0"/>
        <limit effort="30" velocity="1.0"/>
        <axis xyz="0 1 0"/>
    </joint>
    <!-- CASTER WHEEL -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="-${base_width} 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
    </link>

 <!-- CAMEAR -->

    <link name="camera_link">
        <!-- <visual>
            <origin xyz="-0.03 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.06 0.15 0.15" />
            </geometry>
            <material name="white" />
        </visual> -->
        <visual>
            <origin xyz="0.03 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="0.06" radius="0.04" />
            </geometry>
            <material name="blue" />
        </visual>
        <!-- <collision>
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.12 0.15 0.15" />
            </geometry>
        </collision> -->
        <!-- <xacro:box_inertia m="0.1" w="0.12" h="0.15" d="0.15" /> -->

    </link>
    <joint name="camera_joint" type="fixed">
        <origin xyz="0 0 0.25" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>        
    </joint>

    <xacro:include filename="my_2roues-gazebo.xacro" /> 

</robot>
